version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    environment:
      - PORT=5000
      - MONGO_URL=mongodb+srv://hm124501_db_user:sampla124501@cluster0.vnye586.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - NODE_ENV=development
      - JWT_SECRET=chandermanimishra91
      - JWT_EXPIRY=7d
      - CLOUDINARY_CLOUD_NAME=dctjousyt
      - CLOUDINARY_API_KEY=793752349595938
      - CLOUDINARY_API_SECRET=r7rP5FW7n-5aQQauZAgHRxnyL9Q
      - TRANSLATION_API_URL=http://translation:5001
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - translation
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  translation:
    build:
      context: ./AI/AMIT WORK DSU
      dockerfile: Dockerfile.translation
    container_name: translation_service
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    ports:
      - "5001:5001"
    volumes:
      - ./AI/AMIT WORK DSU:/app
    restart: always

